<a href="https://colab.research.google.com/github/Yohanes222/Data-Analys-Python/blob/main/Data_Cleansing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

KeyboardInterrupt:

In [ ]:
import os
os.getcwd()

'/content'

In [ ]:
df_excel = pd.read_excel('Online Retail Data.xlsx', sheet_name='Online Retail Data', header = 0)
df_excel

,order_id,product_code,product_name,quantity,order_date,price,customer_id
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN
...,...,...,...,...,...,...,...
461768,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN
461769,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN
461770,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN
461771,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN
461772,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN

In [ ]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 461773 entries, 0 to 461772
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      461773 non-null  object
 1   product_code  461773 non-null  object
 2   product_name  459055 non-null  object
 3   quantity      461773 non-null  int64
 4   order_date    461773 non-null  datetime64[ns]
 5   price         461773 non-null  float64
 6   customer_id   360853 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 24.7+ MB

In [ ]:
df_csv = pd.read_csv('Online Retail Data.csv')
df_csv

,order_id,product_code,product_name,quantity,order_date,price,customer_id
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN
...,...,...,...,...,...,...,...
461768,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN
461769,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN
461770,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN
461771,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN
461772,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN

In [ ]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 461773 entries, 0 to 461772
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      461773 non-null  object
 1   product_code  461773 non-null  object
 2   product_name  459055 non-null  object
 3   quantity      461773 non-null  int64
 4   order_date    461773 non-null  object
 5   price         461773 non-null  float64
 6   customer_id   360853 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 24.7+ MB

In [ ]:
pip install gspread

Requirement already satisfied: gspread in /usr/local/lib/python3.13/dist-packages (6.2.1)
Requirement already satisfied: google-auth>=1.12.0 in /usr/local/lib/python3.13/dist-packages (from gspread) (2.49.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /usr/local/lib/python3.13/dist-packages (from gspread) (1.4.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from google-auth>=1.12.0->gspread) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /usr/local/lib/python3.13/dist-packages (from google-auth>=1.12.0->gspread) (50.0.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.13/dist-packages (from google-auth>=1.12.0->gspread) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from google-auth-oauthlib>=0.4.1->gspread) (2.0.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography>=38.0.3->google-auth>=1.12.0->gspread) (2.1.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.13/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread) (0.6.4)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.13/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.3.1)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.32.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth>=1.12.0->gspread) (3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2026.7.22)

In [ ]:
import gspread as gs

In [ ]:
df_csv = pd.read_csv('Online Retail Data.csv')
df_csv

,order_id,product_code,product_name,quantity,order_date,price,customer_id
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN
...,...,...,...,...,...,...,...
461768,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN
461769,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN
461770,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN
461771,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN
461772,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import os
os.getcwd()

'/content'

In [ ]:
df = pd.read_csv('Online Retail Data.csv', header=0)
df

,order_id,product_code,product_name,quantity,order_date,price,customer_id
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN
...,...,...,...,...,...,...,...
461768,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN
461769,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN
461770,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN
461771,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN
461772,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN

In [ ]:
df.iloc[1,2:3]

product_name    RETRO SPOTS BUTTER DISH
Name: 1, dtype: object

In [ ]:
# mengambil beberapa baris tertentu dengan index berupa list
df.iloc[[100,200,300]]

,order_id,product_code,product_name,quantity,order_date,price,customer_id
100,493432,22073,RETRO SPOT STORAGE JAR,1,2010-01-04 12:30:00,3.75,14680.0
200,493435,84558A,3D DOG PICTURE PLAYING CARDS,6,2010-01-04 12:57:00,2.95,13206.0
300,493443,20712,JUMBO BAG WOODLAND ANIMALS,4,2010-01-04 13:39:00,1.95,14527.0

In [ ]:
  # mengambil beberapa baris tertentu dengan index berupa range
  df.iloc[100:105]

,order_id,product_code,product_name,quantity,order_date,price,customer_id
100,493432,22073,RETRO SPOT STORAGE JAR,1,2010-01-04 12:30:00,3.75,14680.0
101,493432,21533,RETRO SPOT LARGE MILK JUG,1,2010-01-04 12:30:00,4.95,14680.0
102,493432,22072,TEA CUP AND SAUCER RETRO SPOT,2,2010-01-04 12:30:00,3.75,14680.0
103,493432,21537,RETRO SPOTS PUDDING BOWL,1,2010-01-04 12:30:00,4.25,14680.0
104,493432,21527,RETRO SPOT TRADITIONAL TEAPOT,5,2010-01-04 12:30:00,7.95,14680.0

In [ ]:
# mengambil semua baris dari baris tertentu ke bawah nya
df.iloc[49000:]

,order_id,product_code,product_name,quantity,order_date,price,customer_id
49000,498589,22168,ORGANISER WOOD ANTIQUE WHITE,12,2010-02-21 15:19:00,7.65,14895.0
49001,498589,21784,SHOE SHINE BOX,2,2010-02-21 15:19:00,9.95,14895.0
49002,498589,21871,SAVE THE PLANET MUG,12,2010-02-21 15:19:00,1.25,14895.0
49003,498589,21877,HOME SWEET HOME MUG,12,2010-02-21 15:19:00,1.25,14895.0
49004,498590,21385,IVORY HANGING DECORATION HEART,6,2010-02-21 15:28:00,0.85,13044.0
...,...,...,...,...,...,...,...
461768,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN
461769,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN
461770,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN
461771,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN
461772,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN

In [ ]:
# mengambil baris dari atas dengna index tertentu
df.iloc[:10]

,order_id,product_code,product_name,quantity,order_date,price,customer_id
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN
5,493413,21723,ALPHABET HEARTS STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
6,493414,21844,RETRO SPOT MUG,36,2010-01-04 10:28:00,2.55,14590.0
7,493414,21533,RETRO SPOT LARGE MILK JUG,12,2010-01-04 10:28:00,4.25,14590.0
8,493414,37508,NEW ENGLAND CERAMIC CAKE SERVER,2,2010-01-04 10:28:00,2.55,14590.0
9,493414,35001G,HAND OPEN SHAPE GOLD,2,2010-01-04 10:28:00,4.25,14590.0

In [ ]:
#mengambil baris terakhir
df.iloc[-1]

order_id                       539992
product_code                    21155
product_name    RED RETROSPOT PEG BAG
quantity                            1
order_date        2010-12-23 17:41:00
price                             2.1
customer_id                       NaN
Name: 461772, dtype: object

In [ ]:
#mengambil 5 baris terakhir
df.iloc[-5:]

,order_id,product_code,product_name,quantity,order_date,price,customer_id
461768,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN
461769,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN
461770,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN
461771,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN
461772,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN

In [ ]:
#menamgil semua baris di atas beberapa baris terakhir
df.iloc[:-10]

,order_id,product_code,product_name,quantity,order_date,price,customer_id
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN
...,...,...,...,...,...,...,...
461758,539991,22970,LONDON BUS COFFEE MUG,2,2010-12-23 16:49:00,2.55,NaN
461759,539991,22423,REGENCY CAKESTAND 3 TIER,1,2010-12-23 16:49:00,12.75,NaN
461760,539991,21629,SQUARE FLOOR CUSHION VINTAGE RED,1,2010-12-23 16:49:00,7.95,NaN
461761,539991,21324,HANGING MEDINA LANTERN SMALL,2,2010-12-23 16:49:00,2.95,NaN
461762,539991,22891,TEA FOR ONE POLKADOT,1,2010-12-23 16:49:00,4.25,NaN

In [ ]:
# mengambil 1 kolom tertentu
df.iloc[:,2]

0                 This is a test product.
1                 RETRO SPOTS BUTTER DISH
2                 This is a test product.
3         PANDA AND BUNNIES STICKER SHEET
4          ELEPHANT TOY WITH BLUE T-SHIRT
                       ...
461768     4 WILDFLOWER BOTANICAL CANDLES
461769              GRAND CHOCOLATECANDLE
461770      FLOWER VINE RAFFIA FOOD COVER
461771            FELT FARM ANIMAL RABBIT
461772              RED RETROSPOT PEG BAG
Name: product_name, Length: 461773, dtype: object

In [ ]:
df_index_nonint = df.copy()
df_index_nonint.set_index('order_id',inplace=True)

In [ ]:
#mengambil baris dengna index non-int tertentu
df_index_nonint.loc[['493413','C493411','539991']]

,product_code,product_name,quantity,order_date,price,customer_id
order_id,,,,,,
493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN
493413,21723,ALPHABET HEARTS STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0
539991,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,1,2010-12-23 16:49:00,3.75,NaN
539991,22970,LONDON BUS COFFEE MUG,2,2010-12-23 16:49:00,2.55,NaN
539991,22423,REGENCY CAKESTAND 3 TIER,1,2010-12-23 16:49:00,12.75,NaN
539991,21629,SQUARE FLOOR CUSHION VINTAGE RED,1,2010-12-23 16:49:00,7.95,NaN
539991,21324,HANGING MEDINA LANTERN SMALL,2,2010-12-23 16:49:00,2.95,NaN
539991,22891,TEA FOR ONE POLKADOT,1,2010-12-23 16:49:00,4.25,NaN
539991,22649,STRAWBERRY FAIRY CAKE TEAPOT,1,2010-12-23 16:49:00,4.95,NaN
539991,35443,RASTA IN BATH W SPLIFF ASHTRAY,1,2010-12-23 16:49:00,0.85,NaN
539991,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-23 16:49:00,4.95,NaN
539991,22802,FAUX FUR CHOCOLATE THROW,1,2010-12-23 16:49:00,19.95,NaN
539991,21616,4 PEAR BOTANICAL DINNER CANDLES,1,2010-12-23 16:49:00,1.25,NaN
539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN
539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN

In [ ]:
# mengambil 1 column tertentu
df_index_nonint.loc[:,'product_name']

order_id
493410             This is a test product.
C493411            RETRO SPOTS BUTTER DISH
493412             This is a test product.
493413     PANDA AND BUNNIES STICKER SHEET
493413      ELEPHANT TOY WITH BLUE T-SHIRT
                        ...
539991      4 WILDFLOWER BOTANICAL CANDLES
539991               GRAND CHOCOLATECANDLE
539992       FLOWER VINE RAFFIA FOOD COVER
539992             FELT FARM ANIMAL RABBIT
539992               RED RETROSPOT PEG BAG
Name: product_name, Length: 461773, dtype: object

In [ ]:
# mengambil beberapa kolom dengna index non-int tertentu
df.loc[:,['order_id','product_code','product_name']]

       order_id product_code                     product_name
0        493410      TEST001          This is a test product.
1       C493411        21539          RETRO SPOTS BUTTER DISH
2        493412      TEST001          This is a test product.
3        493413        21724  PANDA AND BUNNIES STICKER SHEET
4        493413        84578   ELEPHANT TOY WITH BLUE T-SHIRT
...         ...          ...                              ...
461768   539991        21618   4 WILDFLOWER BOTANICAL CANDLES
461769   539991        72741            GRAND CHOCOLATECANDLE
461770   539992        21470    FLOWER VINE RAFFIA FOOD COVER
461771   539992        22258          FELT FARM ANIMAL RABBIT
461772   539992        21155            RED RETROSPOT PEG BAG

[461773 rows x 3 columns]

In [ ]:
df[['order_id','product_code','product_name']]

       order_id product_code                     product_name
0        493410      TEST001          This is a test product.
1       C493411        21539          RETRO SPOTS BUTTER DISH
2        493412      TEST001          This is a test product.
3        493413        21724  PANDA AND BUNNIES STICKER SHEET
4        493413        84578   ELEPHANT TOY WITH BLUE T-SHIRT
...         ...          ...                              ...
461768   539991        21618   4 WILDFLOWER BOTANICAL CANDLES
461769   539991        72741            GRAND CHOCOLATECANDLE
461770   539992        21470    FLOWER VINE RAFFIA FOOD COVER
461771   539992        22258          FELT FARM ANIMAL RABBIT
461772   539992        21155            RED RETROSPOT PEG BAG

[461773 rows x 3 columns]

In [ ]:
df[df['order_id']=='539991']

,order_id,product_code,product_name,quantity,order_date,price,customer_id
461757,539991,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,1,2010-12-23 16:49:00,3.75,NaN
461758,539991,22970,LONDON BUS COFFEE MUG,2,2010-12-23 16:49:00,2.55,NaN
461759,539991,22423,REGENCY CAKESTAND 3 TIER,1,2010-12-23 16:49:00,12.75,NaN
461760,539991,21629,SQUARE FLOOR CUSHION VINTAGE RED,1,2010-12-23 16:49:00,7.95,NaN
461761,539991,21324,HANGING MEDINA LANTERN SMALL,2,2010-12-23 16:49:00,2.95,NaN
461762,539991,22891,TEA FOR ONE POLKADOT,1,2010-12-23 16:49:00,4.25,NaN
461763,539991,22649,STRAWBERRY FAIRY CAKE TEAPOT,1,2010-12-23 16:49:00,4.95,NaN
461764,539991,35443,RASTA IN BATH W SPLIFF ASHTRAY,1,2010-12-23 16:49:00,0.85,NaN
461765,539991,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-23 16:49:00,4.95,NaN
461766,539991,22802,FAUX FUR CHOCOLATE THROW,1,2010-12-23 16:49:00,19.95,NaN
461767,539991,21616,4 PEAR BOTANICAL DINNER CANDLES,1,2010-12-23 16:49:00,1.25,NaN
461768,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN
461769,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN

In [ ]:
df[df['order_id'] == '539991'], [['product_name','quantity']]

(       order_id product_code                         product_name  quantity  \
 461757   539991       84029G  KNITTED UNION FLAG HOT WATER BOTTLE         1
 461758   539991        22970                LONDON BUS COFFEE MUG         2
 461759   539991        22423             REGENCY CAKESTAND 3 TIER         1
 461760   539991        21629     SQUARE FLOOR CUSHION VINTAGE RED         1
 461761   539991        21324         HANGING MEDINA LANTERN SMALL         2
 461762   539991        22891                 TEA FOR ONE POLKADOT         1
 461763   539991        22649         STRAWBERRY FAIRY CAKE TEAPOT         1
 461764   539991        35443       RASTA IN BATH W SPLIFF ASHTRAY         1
 461765   539991        22111         SCOTTIE DOG HOT WATER BOTTLE         1
 461766   539991        22802             FAUX FUR CHOCOLATE THROW         1
 461767   539991        21616      4 PEAR BOTANICAL DINNER CANDLES         1
 461768   539991        21618       4 WILDFLOWER BOTANICAL CANDLES         1
 461769   539991        72741                GRAND CHOCOLATECANDLE         4

                  order_date  price  customer_id
 461757  2010-12-23 16:49:00   3.75          NaN
 461758  2010-12-23 16:49:00   2.55          NaN
 461759  2010-12-23 16:49:00  12.75          NaN
 461760  2010-12-23 16:49:00   7.95          NaN
 461761  2010-12-23 16:49:00   2.95          NaN
 461762  2010-12-23 16:49:00   4.25          NaN
 461763  2010-12-23 16:49:00   4.95          NaN
 461764  2010-12-23 16:49:00   0.85          NaN
 461765  2010-12-23 16:49:00   4.95          NaN
 461766  2010-12-23 16:49:00  19.95          NaN
 461767  2010-12-23 16:49:00   1.25          NaN
 461768  2010-12-23 16:49:00   1.25          NaN
 461769  2010-12-23 16:49:00   1.45          NaN  ,
 [['product_name', 'quantity']])

In [ ]:
df.loc[df['order_id'] == '539991', ['order_id','product_name','quantity']]

       order_id                         product_name  quantity
461757   539991  KNITTED UNION FLAG HOT WATER BOTTLE         1
461758   539991                LONDON BUS COFFEE MUG         2
461759   539991             REGENCY CAKESTAND 3 TIER         1
461760   539991     SQUARE FLOOR CUSHION VINTAGE RED         1
461761   539991         HANGING MEDINA LANTERN SMALL         2
461762   539991                 TEA FOR ONE POLKADOT         1
461763   539991         STRAWBERRY FAIRY CAKE TEAPOT         1
461764   539991       RASTA IN BATH W SPLIFF ASHTRAY         1
461765   539991         SCOTTIE DOG HOT WATER BOTTLE         1
461766   539991             FAUX FUR CHOCOLATE THROW         1
461767   539991      4 PEAR BOTANICAL DINNER CANDLES         1
461768   539991       4 WILDFLOWER BOTANICAL CANDLES         1
461769   539991                GRAND CHOCOLATECANDLE         4

In [ ]:
# mengambil data product dengan nama product tertentu dan qty == 1 dan order id == 539991 dan hanya menampilkan order_id,product_name,quantity
df.loc[(df['product_name'] .str.contains ('TEA')) & (df['quantity'] ==1) & (df['order_id']== '539991'), ['order_id','product_name','quantity']]

       order_id                  product_name  quantity
461762   539991          TEA FOR ONE POLKADOT         1
461763   539991  STRAWBERRY FAIRY CAKE TEAPOT         1

In [ ]:
#mengambil data product dengan nama product tertentu dan hanya menampilkan product_name dan hanya 3 data saja
df.loc[(df['product_name'] .str.contains ('TEA')) | (df['product_name'] .str.contains ('COFFE')), ['product_name']].head(3)

                     product_name
10  RETRO SPOT TRADITIONAL TEAPOT
12  RETRO SPOT TRADITIONAL TEAPOT
22             MOROCCAN TEA GLASS

In [ ]:
# mengambil kedua product dengan nama product tertentu berdasarkan qty lebih dari 10
df[((df['product_name'].str.contains ('TEA')) | (df['product_name'].str.contains ('COFFE'))) & (df['quantity']>10)]

,order_id,product_code,product_name,quantity,order_date,price,customer_id
10,493414,21527,RETRO SPOT TRADITIONAL TEAPOT,12,2010-01-04 10:28:00,6.95,14590.0
22,493427,79000,MOROCCAN TEA GLASS,12,2010-01-04 10:43:00,0.85,13287.0
112,493433,84991,60 TEATIME FAIRY CAKE CASES,24,2010-01-04 12:51:00,0.55,14709.0
305,493443,21527,RETRO SPOT TRADITIONAL TEAPOT,12,2010-01-04 13:39:00,6.95,14527.0
455,493467,84991,60 TEATIME FAIRY CAKE CASES,24,2010-01-04 14:29:00,0.55,13004.0
...,...,...,...,...,...,...,...
459159,539654,84946,ANTIQUE SILVER TEA GLASS ETCHED,18,2010-12-20 17:05:00,1.25,17340.0
459663,539728,22348,TEA BAG PLATE RED RETROSPOT,12,2010-12-21 14:26:00,0.85,16270.0
460395,539750,22114,HOT WATER BOTTLE TEA AND SYMPATHY,210,2010-12-21 15:40:00,9.32,NaN
460927,539920,84946,ANTIQUE SILVER TEA GLASS ETCHED,12,2010-12-23 11:06:00,1.25,14085.0
460978,539933,84991,60 TEATIME FAIRY CAKE CASES,24,2010-12-23 11:24:00,0.55,15235.0

In [ ]:
# pip install pandas
# pip install numpy
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({'visitor_name':['Ivan','Adhitama',np.nan],
                   'event_name':['Rock Concert 2022','Jazz Festival 2021','Pop Party 2022'],
                   'ticket_sold_year':[2022,np.nan,2022],
                   'event_year':[2022,2021,2022],
                   'ticket_type':['Gold','Silver','Bronze'],
                   'ticket_price':[100000.0,50000.0,30000.0]})
df['ticket_sold_year'] = df['ticket_sold_year'].astype('Int64')
df['event_year'] = df['event_year'].astype('Int64')
df['ticket_price'] = df['ticket_price'].astype(float)
df

,visitor_name,event_name,ticket_sold_year,event_year,ticket_type,ticket_price
0,Ivan,Rock Concert 2022,2022,2022,Gold,100000.0
1,Adhitama,Jazz Festival 2021,<NA>,2021,Silver,50000.0
2,NaN,Pop Party 2022,2022,2022,Bronze,30000.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   visitor_name      2 non-null      object
 1   event_name        3 non-null      object
 2   ticket_sold_year  2 non-null      Int64
 3   event_year        3 non-null      Int64
 4   ticket_type       3 non-null      object
 5   ticket_price      3 non-null      float64
dtypes: Int64(2), float64(1), object(3)
memory usage: 282.0+ bytes

In [ ]:
df.dropna()

,visitor_name,event_name,ticket_sold_year,event_year,ticket_type,ticket_price
0,Ivan,Rock Concert 2022,2022,2022,Gold,100000.0

In [ ]:
df.drop(columns=['visitor_name','ticket_sold_year'])

           event_name  event_year ticket_type  ticket_price
0   Rock Concert 2022        2022        Gold      100000.0
1  Jazz Festival 2021        2021      Silver       50000.0
2      Pop Party 2022        2022      Bronze       30000.0

In [ ]:
df = pd.DataFrame({'visitor_name':['Ivan','Adhitama','Christanto','Rio','Tokyo'],
                   'age':[25,np.nan,18,21,25],
                   'event_name':['Rock Concert 2022','Jazz Festival 2021','Pop Party 2022','Rock Concert 2022','Pop Party 2022'],
                   'ticket_sold_year':[2022,2021,2022,2022,2022],
                   'event_year':[2022,2021,2022,2022,2022],
                   'ticket_type':['Gold','Silver','Bronze','Silver','Silver'],
                   'ticket_price':[100000.0,50000.0,30000.0,75000.0,60000.0],
                   'reward_point':[400,350,800,np.nan,250]})
df['age'] = df['age'].astype('Int64')
df['ticket_sold_year'] = df['ticket_sold_year'].astype('Int64')
df['event_year'] = df['event_year'].astype('Int64')
df['ticket_price'] = df['ticket_price'].astype(float)
df['reward_point'] = df['reward_point'].astype('Int64')
df

,visitor_name,age,event_name,ticket_sold_year,event_year,ticket_type,ticket_price,reward_point
0,Ivan,25,Rock Concert 2022,2022,2022,Gold,100000.0,400
1,Adhitama,<NA>,Jazz Festival 2021,2021,2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2022,2022,2022,Bronze,30000.0,800
3,Rio,21,Rock Concert 2022,2022,2022,Silver,75000.0,<NA>
4,Tokyo,25,Pop Party 2022,2022,2022,Silver,60000.0,250

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   visitor_name      5 non-null      object
 1   age               4 non-null      Int64
 2   event_name        5 non-null      object
 3   ticket_sold_year  5 non-null      Int64
 4   event_year        5 non-null      Int64
 5   ticket_type       5 non-null      object
 6   ticket_price      5 non-null      float64
 7   reward_point      4 non-null      Int64
dtypes: Int64(4), float64(1), object(3)
memory usage: 472.0+ bytes

In [ ]:
df['reward_point'] = df['reward_point'].fillna(0)
df

,visitor_name,age,event_name,ticket_sold_year,event_year,ticket_type,ticket_price,reward_point
0,Ivan,25,Rock Concert 2022,2022,2022,Gold,100000.0,400
1,Adhitama,<NA>,Jazz Festival 2021,2021,2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2022,2022,2022,Bronze,30000.0,800
3,Rio,21,Rock Concert 2022,2022,2022,Silver,75000.0,0
4,Tokyo,25,Pop Party 2022,2022,2022,Silver,60000.0,250

In [ ]:
df_mean = df.copy()
df_mean ['age'] = df['age'].fillna(df['age'].mean().round())
df_mean

,visitor_name,age,event_name,ticket_sold_year,event_year,ticket_type,ticket_price,reward_point
0,Ivan,25,Rock Concert 2022,2022,2022,Gold,100000.0,400
1,Adhitama,22,Jazz Festival 2021,2021,2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2022,2022,2022,Bronze,30000.0,800
3,Rio,21,Rock Concert 2022,2022,2022,Silver,75000.0,0
4,Tokyo,25,Pop Party 2022,2022,2022,Silver,60000.0,250

In [ ]:
df_mean = df.copy()
df_mean ['age'] = df_mean['age'].fillna(df_mean['age'].mean().round())
df_mean

TypeError: Invalid value '22.25' for dtype Int64

In [ ]:
df_median = df.copy()
df_median['age'] = df_median['age'].fillna(df_median['age'].median())
df_median

,visitor_name,age,event_name,ticket_sold_year,event_year,ticket_type,ticket_price,reward_point
0,Ivan,25,Rock Concert 2022,2022,2022,Gold,100000.0,400
1,Adhitama,23,Jazz Festival 2021,2021,2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2022,2022,2022,Bronze,30000.0,800
3,Rio,21,Rock Concert 2022,2022,2022,Silver,75000.0,0
4,Tokyo,25,Pop Party 2022,2022,2022,Silver,60000.0,250

In [ ]:
df_modus = df.copy()
df_modus['age'] = df_modus['age'].fillna(df_modus['age'].mode()[0])
df_modus

,visitor_name,age,event_name,ticket_sold_year,event_year,ticket_type,ticket_price,reward_point
0,Ivan,25,Rock Concert 2022,2022,2022,Gold,100000.0,400
1,Adhitama,25,Jazz Festival 2021,2021,2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2022,2022,2022,Bronze,30000.0,800
3,Rio,21,Rock Concert 2022,2022,2022,Silver,75000.0,0
4,Tokyo,25,Pop Party 2022,2022,2022,Silver,60000.0,250

In [ ]:
#pengisian dengan nilai sebelum nya
df_ffilna = df.copy()
df_ffilna['age'] = df_ffilna['age'].fillna(method='ffill')
df_ffilna

/tmp/ipykernel_828/3953735607.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffilna['age'] = df_ffilna['age'].fillna(method='ffill')

,visitor_name,age,event_name,ticket_sold_year,event_year,ticket_type,ticket_price,reward_point
0,Ivan,25,Rock Concert 2022,2022,2022,Gold,100000.0,400
1,Adhitama,25,Jazz Festival 2021,2021,2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2022,2022,2022,Bronze,30000.0,800
3,Rio,21,Rock Concert 2022,2022,2022,Silver,75000.0,0
4,Tokyo,25,Pop Party 2022,2022,2022,Silver,60000.0,250

In [ ]:
#pengisian dengan nilai sesudahnya nya
df_bfill = df.copy()
df_bfill['age'] = df_bfill['age'].fillna(method='bfill')
df_bfill

/tmp/ipykernel_828/2416992995.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill['age'] = df_bfill['age'].fillna(method='bfill')

,visitor_name,age,event_name,ticket_sold_year,event_year,ticket_type,ticket_price,reward_point
0,Ivan,25,Rock Concert 2022,2022,2022,Gold,100000.0,400
1,Adhitama,18,Jazz Festival 2021,2021,2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2022,2022,2022,Bronze,30000.0,800
3,Rio,21,Rock Concert 2022,2022,2022,Silver,75000.0,0
4,Tokyo,25,Pop Party 2022,2022,2022,Silver,60000.0,250

In [ ]:
df = pd.DataFrame({'visitor_name':['Ivan','Adhitama','Christanto','Ivan','Tokyo'],
                   'age':[25,23,18,25,25],
                   'event_name':['Rock Concert 2022','Jazz Festival 2021','Pop Party 2022','Rock Concert 2022','Pop Party 2022'],
                   'ticket_sold_year':[2022,2021,2022,2022,2022],
                   'event_year':[2022,2021,2022,2022,2022],
                   'ticket_type':['Gold','Silver','Bronze','Silver','Silver'],
                   'ticket_price':[100000.0,50000.0,30000.0,75000.0,60000.0],
                   'reward_point':[400,350,800,0,250]})
df['age'] = df['age'].astype('Int64')
df['ticket_sold_year'] = df['ticket_sold_year'].astype('Int64')
df['event_year'] = df['event_year'].astype('Int64')
df['ticket_price'] = df['ticket_price'].astype(float)
df['reward_point'] = df['reward_point'].astype('Int64')
df

,visitor_name,age,event_name,ticket_sold_year,event_year,ticket_type,ticket_price,reward_point
0,Ivan,25,Rock Concert 2022,2022,2022,Gold,100000.0,400
1,Adhitama,23,Jazz Festival 2021,2021,2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2022,2022,2022,Bronze,30000.0,800
3,Ivan,25,Rock Concert 2022,2022,2022,Silver,75000.0,0
4,Tokyo,25,Pop Party 2022,2022,2022,Silver,60000.0,250

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   visitor_name      5 non-null      object
 1   age               5 non-null      Int64
 2   event_name        5 non-null      object
 3   ticket_sold_year  5 non-null      Int64
 4   event_year        5 non-null      Int64
 5   ticket_type       5 non-null      object
 6   ticket_price      5 non-null      float64
 7   reward_point      5 non-null      Int64
dtypes: Int64(4), float64(1), object(3)
memory usage: 472.0+ bytes

In [ ]:
df.drop_duplicates(subset='visitor_name', keep='first', inplace=False)
df

,visitor_name,age,event_name,ticket_sold_year,event_year,ticket_type,ticket_price,reward_point
0,Ivan,25,Rock Concert 2022,2022,2022,Gold,100000.0,400
1,Adhitama,23,Jazz Festival 2021,2021,2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2022,2022,2022,Bronze,30000.0,800
4,Tokyo,25,Pop Party 2022,2022,2022,Silver,60000.0,250

In [ ]:
df2 = df.copy()
df2.drop_duplicates(subset='visitor_name', keep='last', inplace=True)
df2

,visitor_name,age,event_name,ticket_sold_year,event_year,ticket_type,ticket_price,reward_point
1,Adhitama,23,Jazz Festival 2021,2021,2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2022,2022,2022,Bronze,30000.0,800
3,Ivan,25,Rock Concert 2022,2022,2022,Silver,75000.0,0
4,Tokyo,25,Pop Party 2022,2022,2022,Silver,60000.0,250

In [ ]:
df3 = df.copy()
df3.drop_duplicates(subset='visitor_name', keep=False, inplace=True)
df3

,visitor_name,age,event_name,ticket_sold_year,event_year,ticket_type,ticket_price,reward_point
1,Adhitama,23,Jazz Festival 2021,2021,2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2022,2022,2022,Bronze,30000.0,800
4,Tokyo,25,Pop Party 2022,2022,2022,Silver,60000.0,250

In [ ]:
df = pd.DataFrame({'visitor_name':['Ivan','Adhitama','Christanto','Ivan','Tokyo'],
                   'age':[25,23,18,25,25],
                   'event_name':['Rock Concert 2022','Jazz Festival 2021','Pop Party 2022','Rock Concert 2022','Pop Party 2022'],
                   'ticket_sold_year':[2022,2021,2022,2022,2022],
                   'event_year':[2022,2021,2022,2022,2022],
                   'ticket_type':['Gold','Silver','Bronze','Gold','Silver'],
                   'ticket_price':[100000.0,50000.0,30000.0,100000.0,60000.0],
                   'reward_point':[400,350,800,400,250]})
df['age'] = df['age'].astype('Int64')
df['ticket_sold_year'] = df['ticket_sold_year'].astype('Int64')
df['event_year'] = df['event_year'].astype('Int64')
df['ticket_price'] = df['ticket_price'].astype(float)
df['reward_point'] = df['reward_point'].astype('Int64')
df

,visitor_name,age,event_name,ticket_sold_year,event_year,ticket_type,ticket_price,reward_point
0,Ivan,25,Rock Concert 2022,2022,2022,Gold,100000.0,400
1,Adhitama,23,Jazz Festival 2021,2021,2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2022,2022,2022,Bronze,30000.0,800
3,Ivan,25,Rock Concert 2022,2022,2022,Gold,100000.0,400
4,Tokyo,25,Pop Party 2022,2022,2022,Silver,60000.0,250

In [ ]:
df.drop_duplicates(inplace=True)
df

,visitor_name,age,event_name,ticket_sold_year,event_year,ticket_type,ticket_price,reward_point
0,Ivan,25,Rock Concert 2022,2022,2022,Gold,100000.0,400
1,Adhitama,23,Jazz Festival 2021,2021,2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2022,2022,2022,Bronze,30000.0,800
4,Tokyo,25,Pop Party 2022,2022,2022,Silver,60000.0,250

In [ ]:
df = pd.DataFrame({'visitor_name':['Ivan','Adhitama','Christanto','Rio','Tokyo'],
                   'age':[25,23,18,21,25],
                   'event_name':['Rock Concert 2022','Jazz Festival 2021','Pop Party 2020','Rock Concert 2022','Pop Party 2020'],
                   'ticket_sold_year':[2022,2021,2020,2022,2020],
                   'event_year':[2022,2021,2020,2022,2020],
                   'ticket_type':['Gold','Silver','Bronze','Gold','Silver'],
                   'ticket_price':[100000.0,50000.0,30000.0,100000.0,60000.0],
                   'reward_point':[400,350,800,100,100]})
df['age'] = df['age'].astype('Int64')
df['ticket_sold_year'] = df['ticket_sold_year'].astype('Int64')
df['event_year'] = df['event_year'].astype('Int64')
df['ticket_price'] = df['ticket_price'].astype(float)
df['reward_point'] = df['reward_point'].astype('Int64')
df

,visitor_name,age,event_name,ticket_sold_year,event_year,ticket_type,ticket_price,reward_point
0,Ivan,25,Rock Concert 2022,2022,2022,Gold,100000.0,400
1,Adhitama,23,Jazz Festival 2021,2021,2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2020,2020,2020,Bronze,30000.0,800
3,Rio,21,Rock Concert 2022,2022,2022,Gold,100000.0,100
4,Tokyo,25,Pop Party 2020,2020,2020,Silver,60000.0,100

In [ ]:
#pip install fast-ml
from fast_ml.feature_selection import get_duplicate_features

In [ ]:
df1 = df.copy()
# mendapatkan kolom-kolom dengan duplikasi values
duplicate_features = get_duplicate_features(df1)
print('Duplikasi kolom:\n')
print(duplicate_features)

# semua kolom dengan duplikasi values sebagai list
duplicate_features_list = duplicate_features.loc[duplicate_features['Desc']=='Duplicate Values', 'feature2'].to_list()
print('\nList kolom duplikasi values:\n')
print(duplicate_features_list)

# hapus semua kolom dengan duplikasi values
print('\nBanyaknya kolom sebelum penghapusan kolom duplikasi values: ' + str(df1.shape[1]))
df1.drop(columns=duplicate_features_list, inplace=True)
print('Banyaknya kolom setelah penghapusan kolom duplikasi values: ' + str(df1.shape[1]))
df1

Duplikasi kolom:

               Desc          feature1          feature2
0  Duplicate Values  ticket_sold_year        event_year
1   Duplicate Index        event_name  ticket_sold_year
2   Duplicate Index        event_name        event_year

List kolom duplikasi values:

['event_year']

Banyaknya kolom sebelum penghapusan kolom duplikasi values: 8
Banyaknya kolom setelah penghapusan kolom duplikasi values: 7

,visitor_name,age,event_name,ticket_sold_year,ticket_type,ticket_price,reward_point
0,Ivan,25,Rock Concert 2022,2022,Gold,100000.0,400
1,Adhitama,23,Jazz Festival 2021,2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2020,2020,Bronze,30000.0,800
3,Rio,21,Rock Concert 2022,2022,Gold,100000.0,100
4,Tokyo,25,Pop Party 2020,2020,Silver,60000.0,100

In [ ]:
df2 = df.copy()
# mendapatkan kolom-kolom dengan duplikasi values
duplicate_index_features = get_duplicate_features(df2)
print('Duplikasi kolom:\n')
print(duplicate_index_features)

# semua kolom dengan duplikasi values sebagai list
duplicate_index_features_list = duplicate_index_features.loc[duplicate_index_features['Desc']=='Duplicate Index', 'feature2'].to_list()
print('\nList kolom duplikasi index:\n')
print(duplicate_index_features_list)

# hapus semua kolom dengan duplikasi values
print('\nBanyaknya kolom sebelum penghapusan kolom duplikasi index: ' + str(df2.shape[1]))
df2.drop(columns=duplicate_index_features_list, inplace=True)
print('Banyaknya kolom setelah penghapusan kolom duplikasi index: ' + str(df2.shape[1]))
df2

Duplikasi kolom:

               Desc          feature1          feature2
0  Duplicate Values  ticket_sold_year        event_year
1   Duplicate Index        event_name  ticket_sold_year
2   Duplicate Index        event_name        event_year

List kolom duplikasi index:

['ticket_sold_year', 'event_year']

Banyaknya kolom sebelum penghapusan kolom duplikasi index: 8
Banyaknya kolom setelah penghapusan kolom duplikasi index: 6

,visitor_name,age,event_name,ticket_type,ticket_price,reward_point
0,Ivan,25,Rock Concert 2022,Gold,100000.0,400
1,Adhitama,23,Jazz Festival 2021,Silver,50000.0,350
2,Christanto,18,Pop Party 2020,Bronze,30000.0,800
3,Rio,21,Rock Concert 2022,Gold,100000.0,100
4,Tokyo,25,Pop Party 2020,Silver,60000.0,100

In [ ]:
df = pd.DataFrame({'quantity':['100','250']})
df.info()
df['quantity'] = df['quantity'].astype(int)
print('\n')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   quantity  2 non-null      object
dtypes: object(1)
memory usage: 148.0+ bytes


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   quantity  2 non-null      int64
dtypes: int64(1)
memory usage: 148.0 bytes

In [ ]:
df = pd.DataFrame({'date':['20220810','20220815']})
df.info()
df['date'] = pd.to_datetime(df['date'], format='%Y%m%d')
print('\n')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    2 non-null      object
dtypes: object(1)
memory usage: 148.0+ bytes


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    2 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 148.0 bytes

In [ ]:
df = pd.DataFrame({'product_name':['ICE TEA','Ice Tea','ice tea']})
print(df)
df['product_name'] = df['product_name'].str.upper()
print('\n')
print(df)

  product_name
0      ICE TEA
1      Ice Tea
2      ice tea


  product_name
0      ICE TEA
1      ICE TEA
2      ICE TEA

In [ ]:
df = pd.DataFrame({'product_name':['ICE TEA','Ice Tea','ice tea']})
print(df)
df['product_name'] = df['product_name'].str.lower()
print('\n')
print(df)

  product_name
0      ICE TEA
1      Ice Tea
2      ice tea


  product_name
0      ice tea
1      ice tea
2      ice tea

In [ ]:
df = pd.DataFrame({'product_name':['   ICE TEA   ','ICE COFFEE   ','    RAINBOW CAKE']})
print(df)
df['product_name'] = df['product_name'].str.strip()
print('\n')
print(df)

       product_name
0        ICE TEA
1     ICE COFFEE
2      RAINBOW CAKE


   product_name
0       ICE TEA
1    ICE COFFEE
2  RAINBOW CAKE

In [ ]:
df = pd.DataFrame({'product_name':['ICE TEA (SOLD PER 1 GLASS)','RAINBOW CAKE (SOLD PER 1 SLICE)']})
print(df)
df['product_name'] = df['product_name'].str.replace(r' \(SOLD.*', '', regex=True)
print('\n')
print(df)

                      product_name
0       ICE TEA (SOLD PER 1 GLASS)
1  RAINBOW CAKE (SOLD PER 1 SLICE)


   product_name
0       ICE TEA
1  RAINBOW CAKE

In [ ]:
df = pd.DataFrame({'address':['jln. harapan','jl. baru']})
print(df)
df['address'] = df['address'].str.replace(r'jl.* ', 'jalan ', regex=True)
print('\n')
print(df)

        address
0  jln. harapan
1      jl. baru


  address
0
1